platform :ios, '8.0'

pod 'AFNetworking', '~> 2.5.0'
pod 'SDWebImage', '~> 3.7.3'
pod 'SwipeBack'
pod 'TPKeyboardAvoiding'
pod 'MBProgressHUD'
pod 'ReactiveCocoa', '~> 2.5'
pod 'Masonry', '~> 0.6.2'
pod 'SFHFKeychainUtils'
pod 'Mantle', '1.5.4'
pod 'FMDB', '~> 2.5'
pod 'libqrencode', '~> 3.4.2'
pod 'UIAlertView+Block', '~> 1.1.0'
pod 'CocoaAsyncSocket'
pod 'CocoaLumberjack', '~> 2.0.1'
pod 'Base64nl', '~> 1.2'
#pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'
pod 'Crashlytics', '~> 3.6.0'
pod 'Fabric', '~> 1.6.4'
pod 'CYLTabBarController', '~> 1.0.5'
pod 'MJRefresh', '~> 3.1.0'
pod 'TCCopyableLabel'